version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: "database"
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kayakto19
      MONGO_INITDB_ROOT_PASSWORD: kayakto20
    volumes:
      - db-data:/data/db
      - ./test-data/:/docker-entrypoint-initdb.d/
    networks:
      - main-network

  api-java:
    container_name: 'java-spring'
    build:
      context: .
      dockerfile: Dockerfile-java
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:pwd@database:27017/assistiveServiseIVR?authSource=assistiveServiseIVR
      BASE_URL: https://pincode-dev.ru/ivr-hor
      SPRINGDOC_SWAGGER_UI_PATH: /ivr-hor/swagger-ui.html
      SPRINGDOC_API_DOCS_PATH: /ivr-hor/v3/api-docs
    ports:
      - 8080:8080
    networks:
      - main-network

volumes:
  db-data:
    driver: local

networks:
  main-network:
    driver: bridge



