# version: '3.8'

services:
  database_mongo:
    image: mongo:latest
    container_name: "database_mongo"
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kayakto19
      MONGO_INITDB_ROOT_PASSWORD: kayakto20
    volumes:
      - db-data:/data/db
      - ./test-data/:/docker-entrypoint-initdb.d/
    networks:
      - main-network

  api-java-ivr:
    container_name: 'java-spring-ivr'
    build:
      context: .
      dockerfile: Dockerfile-java
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:pwd@database_mongo:27017/assistiveServiseIVR?authSource=assistiveServiseIVR
#      BASE_URL: https://pincode-dev.ru/ivr-hor
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_CONFIG_URL: /v3/api-docs/swagger-config
      SPRINGDOC_SWAGGER_UI_URL: /v3/api-docs
      FLASK_API_URL: http://api-flask-vector:5005
#      SERVER_SERVLET_CONTEXT_PATH: /ivr-hor
    ports:
      - "8080:8080"
    networks:
      - main-network

  api-flask-vector:
    container_name: 'flask-api-vector'
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      MONGO_URI: mongodb://user:pwd@database_mongo:27017/assistiveServiseIVR?authSource=assistiveServiseIVR
    ports:
      - "5005:5005"
    networks:
      - main-network

volumes:
  db-data:
    driver: local

networks:
  main-network:
    driver: bridge



