FROM python:3.9
WORKDIR /app
COPY flask-api/ .
RUN pip install --no-cache-dir -r requirements.txt
# Установите переменную окружения для Flask
ENV FLASK_APP=main.py
# Запустите приложение Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5004"]
